# Generated by Django 6.0.6 on 2026-06-20 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TarjetaPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('profesion', models.CharField(max_length=200)),
                ('color', models.CharField(default='#ff9a9e', max_length=20)),
                ('likes', models.IntegerField(default=0)),
            ],
        ),
    ]
