# Generated by Django 6.0.6 on 2026-06-20 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarjetaperfil',
            name='foto_perfil',
            field=models.ImageField(blank=True, default='perfiles/default.png', upload_to='perfiles/'),
        ),
    ]
