# Generated by Django 6.0.6 on 2026-06-20 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0004_alter_tarjetaperfil_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarjetaperfil',
            name='biografia',
            field=models.TextField(blank=True, default='¡Hola! Estoy usando el Muro de Talentos.', max_length=300),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='texto',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tarjetaperfil',
            name='color',
            field=models.CharField(default='#7b2cbf', max_length=7),
        ),
        migrations.AlterField(
            model_name='tarjetaperfil',
            name='profesion',
            field=models.CharField(max_length=100),
        ),
    ]
