# Generated by Django 6.0.6 on 2026-06-20 21:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0005_tarjetaperfil_biografia_alter_comentario_texto_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='texto',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tarjetaperfil',
            name='biografia',
            field=models.TextField(blank=True, default='¡Hola! Estoy usando el Muro de Talentos.'),
        ),
        migrations.AlterField(
            model_name='tarjetaperfil',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarjetas', to=settings.AUTH_USER_MODEL),
        ),
    ]
