# Generated by Django 6.0.6 on 2026-06-20 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0006_alter_comentario_texto_alter_tarjetaperfil_biografia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=200)),
                ('completada', models.BooleanField(default=False)),
                ('creada_el', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
